"""Generates addon/shadow_page.conf: the Acid shadow-mode GUI for force-shadow.

Style td3 (yellow chassis, charcoal boxes, red buttons -- the web panel's look).
Two pages, each a SEQUENCER box plus the same GLOBAL box. Keys/ranges mirror
web/params.json / src/host_shim.cpp's PARAMS. int_values=1: the host's control
socket (--ctrl-sock) takes integers -- enums by option index, float params
topping out at 1.0 (density/accent/slide/gate/jitter) in PERCENT.

  python3 scripts/gen_shadow_page.py            # rewrites addon/shadow_page.conf
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "addon" / "shadow_page.conf"

HEADER = '''# force-acid shadow-mode page -- GENERATED by scripts/gen_shadow_page.py, edit that instead.
#
# Tabs: SEQ A, SEQ B (each with the GLOBAL box). Style td3: the web panel's look
# (yellow chassis, charcoal boxes, red buttons, black engine pill). int_values=1: acid's ctrl socket takes
# option indices for enums and percent for 0..1 floats.
page=5
ctrl_sock=/tmp/acid_ctrl.sock
display_name="ACID"
style=td3
theme_bg=f5c400
theme_panel=f5c400
theme_line=0a0a0a
theme_ink=f0ede4
theme_ink_dim=9a9689
theme_ink_faint=5a5648
theme_accent=f5c400
theme_accent_hi=ffe066
theme_knob_face=2a2a2a
theme_knob_ring=050505
theme_bar=d9ac00
theme_seg_active=f5c400
theme_seg_inactive=2a2a2a
theme_seg_active_tx=0a0a0a
theme_btn_text=ffffff
theme_well=0a0a0a
theme_knob_off=4a4a4a
theme_tab_on=1f1f1f
theme_lcd=0a0a0a
theme_box=1f1f1f
theme_btn_bg=e8341c
theme_chrome_ink=0a0a0a
theme_go_on=35d07f
theme_go_off=e8341c
theme_tabs=d9ac00
int_values=1
engine_process_name=force-acid
engine_nsmodule_path=/media/662522/AddOns/ForceAcid/NSMODULE.json
engine_dirname=ForceAcid
engine_arguments_json=[{"NAME":"verbose param logging","VALUE":"-v"},{"NAME":"ctrl-sock flag","VALUE":"--ctrl-sock"},{"NAME":"control socket path","VALUE":"/tmp/acid_ctrl.sock"}]
'''

Y, H = 88, 624
SEQ_X, SEQ_W = 36, 800          # SEQ frame (left)
GL_X, GL_W = 856, 388           # GLOBAL frame (right)
lines = []


def emit(s):
    lines.append(s)


def frame(x, w, title):
    emit(f'frame x={x} y={Y} w={w} h={H} title="{title}"')


def knob(cx, cy, label, key, lo, hi, val, r=38):
    pct = round(100 * (val - lo) / (hi - lo))
    emit(f'knob cx={cx} cy={cy} r={r} label="{label}" key={key} min={lo} max={hi} pct={pct}')


def stepper(cx, cy, label, key, w=320):
    emit(f'stepper cx={cx} cy={cy} w={w} h=48 label="{label}" key={key} get={key}_txt '
         f'idx={key} count={key}_n min=0 max=1 numbered=0')


def seq_frame(p, letter):
    x, w = SEQ_X, SEQ_W
    frame(x, w, f"SEQUENCER {letter}")
    emit(f'button cx={x + 130} cy=170 label="GENERATE" key={p}_generate')
    emit(f'button cx={x + 330} cy=170 label="MUTATE" key={p}_mutate')
    stepper(x + 200, 265, "REGEN", f"{p}_auto_gen", w=300)
    emit(f'enum_h cx={x + w - 190} cy=265 label="DIR" key={p}_dir options="FWD,REV,PENDUL" active=0 sw=80')
    knobs = [("ALGORHYTHM", f"{p}_algo", 1, 16, 1),
             ("DENSITY", f"{p}_density", 0, 100, 50), ("ACCENT", f"{p}_accent", 0, 100, 30),
             ("SLIDE", f"{p}_slide", 0, 100, 20), ("GATE", f"{p}_gate", 5, 100, 50),
             ("OCTAVES", f"{p}_octaves", 1, 3, 2), ("LENGTH", f"{p}_length", 2, 32, 16),
             ("OFFSET", f"{p}_offset", 0, 31, 0),
             ("BLEND A>B", "blend", -63, 64, 0) if p == "a" else ("TUNE OFFSET", "b_tune", -24, 24, 0)]
    step = (w - 60) / 5
    for i, (label, key, lo, hi, val) in enumerate(knobs):
        r, c = divmod(i, 5)
        knob(round(x + 30 + step * (c + .5)), 400 + r * 170, label, key, lo, hi, val)


def global_frame():
    frame(GL_X, GL_W, "GLOBAL")
    cx = GL_X + GL_W // 2
    stepper(cx, 195, "SCALE", "scale")
    stepper(cx, 280, "ROOT", "root")
    emit(f'enum_h cx={cx} cy=370 label="RESET" key=reset_bars options="1 BAR,2 BARS,4 BARS,8 BARS,OFF" active=4 sw=66')
    knob(cx - 95, 455, "SWING", "swing", 50, 75, 50, r=28)
    knob(cx + 95, 455, "JITTER", "jitter", 0, 100, 0, r=28)
    knob(cx - 95, 560, "A CHANNEL", "a_channel", 1, 16, 1, r=28)
    knob(cx + 95, 560, "B CHANNEL", "b_channel", 1, 16, 1, r=28)
    emit(f'toggle cx={cx} cy=655 label="CV MODE" key=cv_mode on=0')


for name, p, letter in (("SEQ A", "a", "A"), ("SEQ B", "b", "B")):
    emit(f'[tab {name}]')
    seq_frame(p, letter)
    global_frame()      # same GLOBAL box on both pages; the host is the source of truth
    emit("")

OUT.write_text(HEADER + "\n" + "\n".join(lines) + "\n")
print("wrote", OUT)
