#!/usr/bin/env python3
"""Generates addon/shadow_page.conf: the Acid shadow-mode GUI for force-shadow.

Same three-column plate layout as force-maze's page, styled after the web
panel (web/static/style.css: yellow chassis, near-black panels, yellow titles).
Keys/ranges mirror web/params.json / src/host_shim.cpp's PARAMS. int_values=1:
the host's control socket (--ctrl-sock) takes integers -- enums by option
index, float params topping out at 1.0 (density/accent/slide/gate/jitter) in
PERCENT.

  python3 scripts/gen_shadow_page.py            # rewrites addon/shadow_page.conf
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "addon" / "shadow_page.conf"

HEADER = '''# force-acid shadow-mode page -- GENERATED by scripts/gen_shadow_page.py, edit that instead.
#
# Tabs: SEQ A, SEQ B, GLOBAL. Style: the web panel's TD-3 look (yellow chassis,
# near-black panels, yellow accents). int_values=1: acid's ctrl socket takes
# option indices for enums and percent for 0..1 floats.
page=5
ctrl_sock=/tmp/acid_ctrl.sock
display_name="ACID"
theme_bg=161616
theme_panel=0d0d0d
theme_line=7a6200
theme_ink=f0ede4
theme_ink_dim=9a9689
theme_ink_faint=6b6759
theme_accent=f5c400
theme_accent_hi=ffe066
theme_knob_face=2a2a2a
theme_knob_ring=050505
theme_bar=0d0d0d
theme_seg_active=f5c400
theme_seg_inactive=2a2a2a
theme_seg_active_tx=0a0a0a
theme_btn_text=0a0a0a
theme_well=0a0a0a
theme_knob_off=4a4a4a
theme_tab_on=2b2400
theme_lcd=0a0a0a
int_values=1
engine_process_name=force-acid
engine_nsmodule_path=/media/662522/AddOns/ForceAcid/NSMODULE.json
engine_dirname=ForceAcid
engine_arguments_json=[{"NAME":"verbose param logging","VALUE":"-v"},{"NAME":"ctrl-sock flag","VALUE":"--ctrl-sock"},{"NAME":"control socket path","VALUE":"/tmp/acid_ctrl.sock"}]
'''

Y, H = 88, 624
FRAMES = [(36, 389), (445, 389), (854, 389)]   # x, w
COL = [x + w // 2 for x, w in FRAMES]           # frame centres
lines = []


def emit(s):
    lines.append(s)


def frame(i, title):
    x, w = FRAMES[i]
    emit(f'frame x={x} y={Y} w={w} h={H} title="{title}"')


def knob(cx, cy, label, key, lo, hi, val, r=39):
    pct = round(100 * (val - lo) / (hi - lo))
    emit(f'knob cx={cx} cy={cy} r={r} label="{label}" key={key} min={lo} max={hi} pct={pct}')


def stepper(cx, cy, label, key, w=320):
    emit(f'stepper cx={cx} cy={cy} w={w} h=48 label="{label}" key={key} get={key}_txt '
         f'idx={key} count={key}_n min=0 max=1 numbered=0')


def seq_tab(name, p, a):
    emit(f'[tab {name}]')
    frame(0, "GENERATOR"); frame(1, "PATTERN"); frame(2, "LENGTH / MIX")
    c = COL[0]
    emit(f'button cx={c} cy=185 label="GENERATE" key={p}_generate')
    emit(f'button cx={c} cy=255 label="MUTATE" key={p}_mutate')
    stepper(c, 375, "REGEN", f"{p}_auto_gen")
    emit(f'enum_h cx={c} cy=490 label="DIR" key={p}_dir options="FWD,REV,PENDUL" active=0 sw=100')
    knob(c, 620, f"ALGO {name[-1]}", f"{p}_algo", 1, 16, 1)
    l, r = COL[1] - 98, COL[1] + 98
    knob(l, 232, "DENSITY", f"{p}_density", 0, 100, 50)
    knob(r, 232, "ACCENT", f"{p}_accent", 0, 100, 30)
    knob(l, 420, "SLIDE", f"{p}_slide", 0, 100, 20)
    knob(r, 420, "GATE", f"{p}_gate", 5, 100, 50)
    knob(l, 608, "OCTAVES", f"{p}_octaves", 1, 3, 2)
    knob(r, 608, "CHANNEL", f"{p}_channel", 1, 16, 1)
    l, r = COL[2] - 98, COL[2] + 98
    knob(l, 232, "LENGTH", f"{p}_length", 2, 32, 16)
    knob(r, 232, "OFFSET", f"{p}_offset", 0, 31, 0)
    if p == "a":
        knob(COL[2], 420, "BLEND A>B", "blend", -63, 64, 0)
    else:
        knob(COL[2], 420, "TUNE OFFSET", "b_tune", -24, 24, 0)
    emit("")


seq_tab("SEQ A", "a", None)
seq_tab("SEQ B", "b", None)

emit('[tab GLOBAL]')
frame(0, "KEY"); frame(1, "FEEL"); frame(2, "OUTPUT")
stepper(COL[0], 230, "SCALE", "scale")
stepper(COL[0], 380, "ROOT", "root")
emit(f'enum_h cx={COL[0]} cy=530 label="RESET" key=reset_bars options="1 BAR,2 BARS,4 BARS,8 BARS,OFF" active=4 sw=68')
knob(COL[1], 260, "SWING", "swing", 50, 75, 50, r=45)
knob(COL[1], 500, "JITTER", "jitter", 0, 100, 0, r=45)
emit(f'toggle cx={COL[2]} cy=300 label="CV MODE" key=cv_mode on=0')

OUT.write_text(HEADER + "\n" + "\n".join(lines) + "\n")
print("wrote", OUT)
